install_data(
  'hicolor' / 'scalable' / 'apps' / 'io.github.stevenleadbeater.LoyaltyCardApp.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps',
)

install_data(
  'hicolor' / 'symbolic' / 'apps' / 'io.github.stevenleadbeater.LoyaltyCardApp-symbolic.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'symbolic' / 'apps',
)
